version: '3'
services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  node2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
  node3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
